import { readFileSync, writeFileSync } from "node:fs";
import type { DailySchedule, Question } from "../lib/types";

/**
 * Turns data/daily-sets.json into supabase/seed-daily.sql.
 *
 * The daily schedule is content, not schema: it changes often and is authored
 * by hand, so it is regenerated into one idempotent seed script rather than an
 * ever-growing pile of migrations. Run this after editing the JSON, then apply
 * the SQL to the database so the server can rescore daily rounds.
 */

const SOURCE = new URL("../data/daily-sets.json", import.meta.url);
const TARGET = new URL("../supabase/seed-daily.sql", import.meta.url);

const schedule = JSON.parse(readFileSync(SOURCE, "utf8")) as DailySchedule;

/** Postgres string literal, quoting any embedded apostrophes. */
const lit = (value: string) => `'${value.replace(/'/g, "''")}'`;

const nullable = (value: string | undefined) =>
  value === undefined || value === null ? "null" : lit(value);

/** One row of the questions VALUES list. */
function questionRow(question: Question) {
  return `  (${[
    lit(question.id),
    lit(question.category),
    lit(question.measure),
    lit(question.subtype),
    lit(question.prompt),
    question.answer,
    question.min,
    question.max,
    lit(question.scale),
    lit(question.unit),
    nullable(question.referenceYear),
    lit(question.source.title),
    lit(question.source.url),
    lit(question.explanation),
    "true",
  ].join(", ")})`;
}

const allQuestions = schedule.sets.flatMap((set) => set.questions);
const dates = schedule.sets.map((set) => set.date);

// One multi-row statement per table rather than one per question: the whole
// schedule then fits in a payload small enough to paste into a SQL console.
const blocks: string[] = [
  `-- Generated by scripts/build-daily-sql.ts. Do not edit by hand.
-- Edit data/daily-sets.json, then run \`npm run build:daily-sql\`.
--
-- Safe to re-run: every statement upserts.

begin;`,

  `insert into public.questions (
  id, category, measure, subtype, prompt, answer, min, max, scale, unit,
  reference_year, source_title, source_url, explanation, is_daily
) values
${allQuestions.map(questionRow).join(",\n")}
on conflict (id) do update set
  category       = excluded.category,
  measure        = excluded.measure,
  subtype        = excluded.subtype,
  prompt         = excluded.prompt,
  answer         = excluded.answer,
  min            = excluded.min,
  max            = excluded.max,
  scale          = excluded.scale,
  unit           = excluded.unit,
  reference_year = excluded.reference_year,
  source_title   = excluded.source_title,
  source_url     = excluded.source_url,
  explanation    = excluded.explanation,
  is_daily       = true;`,

  `insert into public.daily_sets (puzzle_date) values
${dates.map((d) => `  (${lit(d)})`).join(",\n")}
on conflict (puzzle_date) do nothing;`,

  // Rebuilt wholesale so a reordered or replaced set leaves no orphans behind.
  `delete from public.daily_set_questions
where puzzle_date in (${dates.map(lit).join(", ")});`,

  `insert into public.daily_set_questions (puzzle_date, question_id, asked_order) values
${schedule.sets
  .flatMap((set) =>
    set.questions.map(
      (question, index) =>
        `  (${lit(set.date)}, ${lit(question.id)}, ${index + 1})`,
    ),
  )
  .join(",\n")};`,

  "commit;",
];

writeFileSync(TARGET, `${blocks.join("\n\n")}\n`, "utf8");

const questionTotal = schedule.sets.reduce(
  (sum, set) => sum + set.questions.length,
  0,
);
console.log(
  `Wrote supabase/seed-daily.sql for ${schedule.sets.length} set(s) and ${questionTotal} daily questions.`,
);
