import { writeFileSync } from "node:fs";
import { createClient } from "@supabase/supabase-js";
import type { Question, QuestionScale, QuestionUnit } from "../lib/types";

/**
 * Regenerates lib/questions.generated.ts from Postgres, which is the source of
 * truth for the bank. Run `npm run generate:questions` after editing questions
 * in the database, then commit the result: the game itself never queries for
 * questions, so a round can be dealt offline and `npm run validate:data` still
 * checks the bank at build time.
 */

const url = process.env.VITE_SUPABASE_URL;
const key = process.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!url || !key) {
  console.error(
    "Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY (see .env.example).",
  );
  process.exit(1);
}

type Row = {
  id: string;
  category: Question["category"];
  subtype: Question["subtype"];
  prompt: string;
  answer: string;
  min: string;
  max: string;
  scale: QuestionScale;
  unit: QuestionUnit;
  reference_year: string | null;
  source_title: string;
  source_url: string;
  explanation: string;
};

const supabase = createClient(url, key, { auth: { persistSession: false } });

// Ordered so the generated file only changes when the data does.
const { data, error } = await supabase
  .from("questions")
  .select(
    "id, category, subtype, prompt, answer, min, max, scale, unit, reference_year, source_title, source_url, explanation",
  )
  .order("category")
  .order("subtype")
  .order("id")
  .returns<Row[]>();

if (error) {
  console.error(`Could not read questions: ${error.message}`);
  process.exit(1);
}

if (!data || data.length === 0) {
  console.error("The questions table is empty; refusing to write an empty bank.");
  process.exit(1);
}

// numeric arrives as a string to preserve precision; the bank stores plain
// numbers, and Number() is exact for every magnitude the bank actually holds.
const num = (value: string) => {
  const parsed = Number(value);
  if (!Number.isFinite(parsed)) {
    throw new Error(`Value ${value} is not a finite number`);
  }
  return parsed;
};

const str = (value: string) => JSON.stringify(value);

const record = (row: Row) => {
  const referenceYear = row.reference_year
    ? `\n    referenceYear: ${str(row.reference_year)},`
    : "";

  return `  {
    id: ${str(row.id)},
    category: ${str(row.category)},
    subtype: ${str(row.subtype)},
    prompt: ${str(row.prompt)},
    answer: ${num(row.answer)},
    min: ${num(row.min)},
    max: ${num(row.max)},
    scale: ${str(row.scale)},
    unit: ${str(row.unit)},${referenceYear}
    source: {
      title: ${str(row.source_title)},
      url: ${str(row.source_url)},
    },
    explanation: ${str(row.explanation)},
  },`;
};

const file = `// Generated by scripts/generate-questions.ts. Do not edit by hand.
// Edit the questions table in Postgres, then run \`npm run generate:questions\`.
import type { Question } from "./types";

export const generatedQuestions: readonly Question[] = [
${data.map(record).join("\n")}
];
`;

writeFileSync(new URL("../lib/questions.generated.ts", import.meta.url), file, "utf8");

console.log(`Generated lib/questions.generated.ts with ${data.length} questions.`);
