-- Imported by scripts/import-questions.ts from C:\Users\Cambo\Downloads\16history.json.

insert into public.questions (
  id, category, measure, subtype, prompt, answer, min, max, scale, unit,
  reference_year, source_title, source_url, explanation, is_daily
) values
  ('history-statue-of-zeus-olympia-height', 'history', 'size', 'length', 'Phidias''s gold-and-ivory Statue of Zeus was so vast that ancient writers joked the god would smash through the roof if he stood up — how tall was it seated?', 12, 3, 30, 'linear', 'metre', null, 'Britannica — Statue of Zeus', 'https://www.britannica.com/topic/Statue-of-Zeus', 'The seated statue stood almost 12 metres tall inside its temple, one of the Seven Wonders of the Ancient World.', false),
  ('history-iliad-book-count', 'history', 'quantity', 'count', 'Ancient scholars split Homer''s entire Iliad into how many separate books?', 24, 4, 60, 'linear', 'count', null, 'Harvard Center for Hellenic Studies — An Outline of the Homeric Iliad', 'https://continuum.fas.harvard.edu/an-outline-of-the-homeric-iliad-designed-especially-for-first-time-readers/', 'The Iliad was divided into 24 books, traditionally said to echo the 24 letters of the Greek alphabet.', false),
  ('history-great-pyramid-original-height', 'history', 'size', 'length', 'Before its gleaming limestone casing was stripped away over the centuries, how tall did the Great Pyramid of Giza originally stand?', 146.5, 50, 300, 'linear', 'metre', null, 'Egypt Ministry of Tourism and Antiquities — The Great Pyramid', 'https://egymonuments.gov.eg/en/monuments/the-great-pyramid', 'The pyramid originally reached 146.5 metres, making it the tallest structure on Earth for roughly 3,800 years.', false),
  ('history-great-pyramid-average-block-weight', 'history', 'size', 'mass', 'Egyptologists estimate that an average limestone block inside the Great Pyramid weighs about how many tonnes?', 2.5, 0.5, 20, 'log', 'tonne', null, 'npj Heritage Science — Sustainability problems of the Giza pyramids', 'https://www.nature.com/articles/s40494-020-0356-9', 'Most Egyptologists use 2.5 tonnes as the average block weight, though some granite blocks weigh far more.', false),
  ('history-hammurabi-code-law-count', 'history', 'quantity', 'count', 'How many individual laws are carved into the towering black stele known as the Code of Hammurabi?', 282, 50, 500, 'linear', 'count', null, 'Louvre Museum — The Code of Hammurabi', 'https://www.louvre.fr/en/the-code-of-hammurabi', 'The stele records 282 legal judgements covering family, property, trade and labour in ancient Babylon.', false),
  ('history-neo-babylonian-empire-duration', 'history', 'physics', 'duration', 'From Nabopolassar''s revolt against Assyria to Cyrus''s conquest, for how many years did the Neo-Babylonian Empire actually last?', 87, 10, 400, 'log', 'duration-year', null, 'Britannica — Neo-Babylonian Empire', 'https://www.britannica.com/place/Neo-Babylonian-Empire', 'The empire lasted 87 years, from Nabopolassar''s coronation in 626 BCE to the Persian conquest in 539 BCE.', false),
  ('history-ishtar-gate-height', 'history', 'size', 'length', 'Nebuchadnezzar II''s dazzling blue Ishtar Gate, covered in glazed dragons and bulls, originally stood how tall?', 12, 3, 40, 'log', 'metre', null, 'Britannica — Ishtar Gate', 'https://britannica.com/topic/Ishtar-Gate', 'The gate stood more than 12 metres high and formed the eighth fortified entrance into the city of Babylon.', false),
  ('history-augustus-standing-legions-count', 'history', 'quantity', 'count', 'After Augustus disbanded Rome''s bloated civil-war armies, how many legions were left in his new professional standing force?', 28, 5, 80, 'linear', 'count', null, 'UNRV Roman History — Augustus and the Legions', 'https://www.unrv.com/early-empire/augustus-legions.php', 'Augustus reduced over 50 legions down to 28 professional units, most of which lasted for centuries.', false),
  ('history-rome-founding-to-fall-duration', 'history', 'physics', 'duration', 'Rome''s founding is traditionally dated to 753 BCE, and its western empire fell in 476 CE — how many years separate the two?', 1229, 200, 2500, 'log', 'duration-year', null, 'Britannica — Ancient Rome', 'https://www.britannica.com/place/ancient-Rome', 'The traditional founding of Rome in 753 BCE and the fall of the Western Roman Empire in 476 CE are 1,229 years apart.', false),
  ('history-roman-empire-peak-area', 'history', 'size', 'area', 'At its absolute widest, under Emperor Trajan in AD 117, how many square kilometres did the Roman Empire cover?', 5000000, 500000, 20000000, 'log', 'square-kilometre', null, 'Wikipedia — Roman Empire (infobox area figures)', 'https://en.wikipedia.org/wiki/Roman_Empire', 'The empire covered about 5 million square kilometres at its peak, stretching from Britain to the Persian Gulf.', false),
  ('history-lindisfarne-raid-year', 'history', 'history', 'event', 'In what year did Norse raiders sack the monastery on Lindisfarne, an attack that shocked all of Christian Europe?', 793, 600, 1100, 'linear', 'year', null, 'English Heritage — The Viking Raid on Lindisfarne', 'https://www.english-heritage.org.uk/visit/places/lindisfarne-priory/History/viking-raid/', 'The raid on Lindisfarne''s monastery in 793 is traditionally seen as marking the start of the Viking Age.', false),
  ('history-gokstad-ship-length', 'history', 'size', 'length', 'The Gokstad ship, the finest Viking longship ever excavated, measures how many metres from bow to stern?', 23.22, 8, 45, 'linear', 'metre', null, 'Museum of the Viking Age — The Gokstad Ship', 'https://www.vikingtidsmuseet.no/english/the-collection/the-gokstad-ship/the-gokstad-ship.html', 'The Gokstad ship measures 23.22 metres long and 5.18 metres wide, built from oak around AD 890.', false),
  ('history-gokstad-ship-oarholes-count', 'history', 'quantity', 'count', 'The Gokstad ship could be rowed by two men sharing each hole along its side — how many oar holes did it have in total?', 32, 4, 80, 'linear', 'count', null, 'Museum of the Viking Age — The Gokstad Ship', 'https://www.vikingtidsmuseet.no/english/the-collection/the-gokstad-ship/the-gokstad-ship.html', 'There are 16 oar holes along each side, 32 in total, giving space for a crew of up to 67 people.', false),
  ('history-cuerdale-hoard-silver-weight', 'history', 'size', 'mass', 'The Cuerdale Hoard, the largest Viking silver hoard known from north-western Europe, weighed roughly how many kilograms?', 40, 1, 200, 'log', 'kilogram', null, 'British Museum Images — The Cuerdale Hoard', 'https://www.bmimages.com/preview.asp?image=00035906001', 'The hoard weighed almost 40 kilograms of silver coins, ingots and hacksilver, buried around AD 905.', false),
  ('history-pictish-symbol-stones-count', 'history', 'quantity', 'count', 'Roughly how many Class I Pictish symbol stones, carved with mysterious animal and geometric designs, survive across Scotland today?', 200, 20, 500, 'linear', 'count', null, 'Historic Environment Scotland — What''s Left of the Picts?', 'https://blog.historicenvironment.scot/2025/08/whats-left-of-the-picts-scotlands-pictish-stones/', 'Around 200 Class I symbol stones survive, carved between the 4th and 7th centuries with designs unique to the Picts.', false),
  ('history-suenos-stone-height', 'history', 'size', 'length', 'Sueno''s Stone near Forres is Scotland''s tallest surviving carved standing stone — how many metres does it reach?', 7, 1, 20, 'linear', 'metre', null, 'Historic Environment Scotland — Sueno''s Stone', 'https://www.historicenvironment.scot/visit-a-place/places/suenos-stone/', 'Sueno''s Stone stands about 7 metres tall, covered in an intricate Pictish cross and a battle scene.', false)
on conflict (id) do nothing;
