-- Imported by scripts/import-questions.ts from C:\Users\Cambo\Downloads\space36newapproved-questions (1).json.
-- Two box-office rows from that pack were reclassified from space to movies
-- before import, and renamed to the movies-money-<film>-worldwide-box-office
-- convention used by the rest of the movies bank.

insert into public.questions (
  id, category, measure, subtype, prompt, answer, min, max, scale, unit,
  reference_year, source_title, source_url, explanation, is_daily
) values
  ('space-count-io-active-volcanoes', 'space', 'quantity', 'count', 'Jupiter''s gravity keeps the moon Io molten inside. About how many active volcanoes does it have?', 400, 50, 2000, 'log', 'count', null, 'NASA Jet Propulsion Laboratory - Juno Mission Uncovers Heart of Jovian Moon''s Volcanic Rage', 'https://www.jpl.nasa.gov/news/nasas-juno-mission-uncovers-heart-of-jovian-moons-volcanic-rage/', 'Io is the most volcanically active body in the Solar System, with roughly 400 active volcanoes driven by tidal heating from Jupiter''s gravity.', false),
  ('space-duration-phobos-orbital-period', 'space', 'physics', 'duration', 'Phobos laps Mars faster than Mars can spin. How many hours does one orbit take?', 7.65, 1, 30, 'linear', 'hour', null, 'NASA Science - Phobos', 'https://science.nasa.gov/mars/moons/phobos/', 'Phobos completes an orbit of Mars in about 7 hours 39 minutes, so quickly that it rises in the west and sets in the east three times a Martian day.', false),
  ('space-length-ganymede-diameter', 'space', 'size', 'length', 'Jupiter''s moon Ganymede is bigger than the planet Mercury. How wide is it, in kilometres?', 5268, 1000, 10000, 'linear', 'kilometre', null, 'NASA Science - Ganymede Facts', 'https://science.nasa.gov/jupiter/jupiter-moons/ganymede/facts/', 'Ganymede measures about 5,268 kilometres across, making it larger than the planet Mercury and the only moon known to generate its own magnetic field.', false),
  ('space-percentage-sun-mass-of-solar-system', 'space', 'quantity', 'percentage', 'What percentage of the Solar System''s total mass is the Sun alone?', 99.8, 0, 100, 'linear', 'percent', null, 'NASA - It''s Surprisingly Hard to Go to the Sun', 'https://www.nasa.gov/solar-system/its-surprisingly-hard-to-go-to-the-sun/', 'The Sun contains about 99.8% of all the mass in the Solar System, with Jupiter accounting for most of what little is left.', false),
  ('space-mass-jupiter', 'space', 'size', 'mass', 'What is Jupiter''s mass, in kilograms?', 1.8986e+27, 1e+26, 5e+27, 'log', 'kilogram', null, 'NASA Radio JOVE Project - Jupiter Fact Sheet', 'https://radiojove.gsfc.nasa.gov/education/educationalcd/Posters&Fliers/FactSheets/JupiterFactSheet.pdf', 'Jupiter has a mass of about 1.8986 x 10^27 kilograms, roughly 318 times the mass of Earth and more than twice the combined mass of every other planet.', false),
  ('space-mass-eris', 'space', 'size', 'mass', 'Eris is the dwarf planet whose discovery got Pluto demoted. What is its mass, in kilograms?', 1.67e+22, 1e+21, 1e+23, 'log', 'kilogram', null, 'NASA Science - Astronomers Measure Mass of Largest Dwarf Planet', 'https://science.nasa.gov/missions/hubble/astronomers-measure-mass-of-largest-dwarf-planet/', 'By tracking Eris''s moon Dysnomia, Hubble and the Keck Observatory measured Eris''s mass at about 1.67 x 10^22 kilograms, roughly 27% more massive than Pluto.', false),
  ('space-length-pluto-diameter', 'space', 'size', 'length', 'New Horizons finally settled Pluto''s true size in 2015. How wide is it, in kilometres?', 2370, 500, 6000, 'linear', 'kilometre', null, 'NASA - New Horizons Spacecraft Nears Historic Pluto Encounter', 'https://www.nasa.gov/news-release/nasas-new-horizons-spacecraft-nears-historic-july-14-encounter-with-pluto/', 'New Horizons measured Pluto''s diameter at about 2,370 kilometres, confirming it as the largest known object beyond Neptune.', false),
  ('space-length-barringer-meteor-crater', 'space', 'size', 'length', 'How wide is Arizona''s Meteor Crater, in kilometres?', 1.186, 0.3, 5, 'linear', 'kilometre', null, 'USRA Lunar and Planetary Institute - Barringer Meteorite Crater', 'https://www.lpi.usra.edu/science/kring/epo_web/impact_cratering/World_Craters_web/northamericacraters/Barringer.html', 'Meteor Crater, also called Barringer Crater, measures about 1.186 kilometres across and formed roughly 50,000 years ago when an iron-nickel meteorite struck northern Arizona.', false),
  ('space-length-vesta-south-pole-mountain', 'space', 'size', 'length', 'How tall is the mountain at the asteroid Vesta''s south pole, in kilometres?', 22, 5, 50, 'linear', 'kilometre', null, 'NASA Jet Propulsion Laboratory - New View of Vesta Mountain From NASA''s Dawn Mission', 'https://www.jpl.nasa.gov/news/new-view-of-vesta-mountain-from-nasas-dawn-mission/', 'NASA''s Dawn spacecraft found that the peak at Vesta''s south pole rises about 22 kilometres above the surrounding terrain, nearly three times the height of Mount Everest.', false),
  ('space-length-comet-bernardinelli-bernstein-nucleus', 'space', 'size', 'length', 'How wide is the largest comet nucleus ever measured, in kilometres?', 137, 20, 400, 'log', 'kilometre', null, 'NASA Science - Hubble Confirms Largest Comet Nucleus Ever Seen', 'https://science.nasa.gov/missions/hubble/hubble-confirms-largest-comet-nucleus-ever-seen/', 'Hubble measured the nucleus of comet Bernardinelli-Bernstein at about 137 kilometres across, roughly 50 times larger than the nucleus of a typical comet.', false),
  ('space-mass-hoba-meteorite', 'space', 'size', 'mass', 'The Hoba meteorite in Namibia is the largest ever found, and has never been moved. How many tonnes does it weigh?', 60, 5, 300, 'log', 'tonne', null, 'Britannica - Hoba Meteorite', 'https://www.britannica.com/topic/Hoba-meteorite', 'The Hoba meteorite weighs about 60 tonnes, making it the largest known meteorite on Earth. It has never been moved since it fell, and weathering has slowly reduced it from an original estimate closer to 66 tonnes.', false),
  ('space-mass-ceres', 'space', 'size', 'mass', 'What is the mass of Ceres, the largest object in the asteroid belt, in kilograms?', 939000000000000000000, 100000000000000000000, 5e+21, 'log', 'kilogram', null, 'NASA Science - Ceres Facts', 'https://science.nasa.gov/dwarf-planets/ceres/facts/', 'Ceres has a mass of about 9.39 x 10^20 kilograms, making up roughly a third of the entire asteroid belt''s mass on its own.', false),
  ('space-length-enceladus-plume-height', 'space', 'size', 'length', 'Geysers on Saturn''s moon Enceladus fire water into space. How far does the plume reach, in kilometres?', 9600, 500, 30000, 'log', 'kilometre', null, 'NASA Science - Webb Maps Surprisingly Large Plume Jetting From Saturn''s Moon Enceladus', 'https://science.nasa.gov/missions/webb/webb-maps-surprisingly-large-plume-jetting-from-saturns-moon-enceladus/', 'The James Webb Space Telescope observed Enceladus venting a water vapour plume more than 9,600 kilometres out into space, over 20 times the width of the moon itself.', false),
  ('space-length-south-pole-aitken-basin', 'space', 'size', 'length', 'How wide is the South Pole-Aitken Basin on the Moon''s far side, in kilometres?', 2500, 500, 6000, 'log', 'kilometre', null, 'Lunar Reconnaissance Orbiter Camera (Arizona State University) - The Moon''s Largest Impact Basin', 'http://lroc.sese.asu.edu/posts/219', 'The South Pole-Aitken Basin spans roughly 2,500 kilometres and plunges more than 8 kilometres deep, covering nearly a quarter of the Moon''s surface.', false),
  ('space-event-crab-nebula-supernova', 'space', 'history', 'event', 'The supernova that made the Crab Nebula was bright enough to see in daylight. In what year was it recorded?', 1054, 900, 1300, 'linear', 'year', null, 'NASA Science - Messier 1 (Crab Nebula)', 'https://science.nasa.gov/mission/hubble/science/explore-the-night-sky/hubble-messier-catalog/messier-1/', 'Chinese and other astronomers recorded a ''guest star'' in the year 1054 that was visible in daylight for weeks. It was the supernova that created the Crab Nebula.', false),
  ('space-event-first-black-hole-image', 'space', 'history', 'event', 'In what year was the first direct image of a black hole released?', 2019, 1990, 2025, 'linear', 'year', null, 'NASA Science - First Image of a Black Hole', 'https://science.nasa.gov/resource/first-image-of-a-black-hole/', 'In April 2019, the Event Horizon Telescope collaboration released the first direct image of a black hole, showing the glowing ring of matter around the supermassive black hole at the centre of galaxy M87.', false),
  ('space-mass-neutron-star-sugar-cube', 'space', 'size', 'mass', 'What would a single sugar cube of neutron star material weigh, in kilograms?', 1000000000000, 10000000000, 100000000000000, 'log', 'kilogram', null, 'NASA Imagine the Universe - Neutron Stars', 'https://imagine.gsfc.nasa.gov/science/objects/neutron_stars1.html', 'NASA states that one sugar cube of neutron star material would weigh about 1 trillion kilograms, roughly the mass of a mountain squeezed into a single cube.', false),
  ('space-temperature-boomerang-nebula', 'space', 'physics', 'temperature', 'How cold is the Boomerang Nebula, the coldest known place in the universe, in degrees Celsius?', -272, -273, 0, 'linear', 'celsius', null, 'ESA/Hubble - The Boomerang Nebula, the Coolest Place in the Universe?', 'https://esahubble.org/images/heic0301a/', 'The Boomerang Nebula measures about -272 degrees Celsius, just one degree above absolute zero, making it colder than even the leftover glow of the Big Bang.', false),
  ('space-count-gaia-stars-mapped', 'space', 'quantity', 'count', 'How many stars did ESA''s Gaia spacecraft catalogue to map the Milky Way?', 2000000000, 100000000, 10000000000, 'log', 'count', null, 'ESA - Gaia Overview', 'https://www.esa.int/Science_Exploration/Space_Science/Gaia_overview', 'Over more than a decade of observations, ESA''s Gaia mission catalogued the positions, motions and brightness of about 2 billion stars in and around the Milky Way.', false),
  ('space-percentage-dark-energy-universe', 'space', 'quantity', 'percentage', 'What percentage of the universe is made up of dark energy?', 68, 0, 100, 'linear', 'percent', null, 'NASA Science - What Is Dark Energy?', 'https://science.nasa.gov/dark-energy/', 'NASA estimates that about 68% of the universe is dark energy, with dark matter making up roughly 27% and all the ordinary matter we can see accounting for less than 5%.', false),
  ('space-count-hubble-ultra-deep-field-galaxies', 'space', 'quantity', 'count', 'Hubble stared at one seemingly empty patch of sky for 11 days. How many galaxies turned up?', 10000, 1000, 100000, 'log', 'count', null, 'NASA Science - Hubble''s Deep Fields', 'https://science.nasa.gov/mission/hubble/science/universe-uncovered/hubble-deep-fields/', 'Hubble''s Ultra Deep Field image, built from over 800 orbits of viewing time, revealed roughly 10,000 galaxies in one small patch of sky, some seen as they looked just a few hundred million years after the Big Bang.', false),
  ('space-event-cosmic-microwave-background-discovery', 'space', 'history', 'event', 'Two Bell Labs engineers kept picking up a hiss they couldn''t explain: the afterglow of the Big Bang. In what year?', 1965, 1900, 2000, 'linear', 'year', null, 'EBSCO Research Starters - Penzias and Wilson Discover Cosmic Microwave Background Radiation', 'https://www.ebsco.com/research-starters/physics/penzias-and-wilson-discover-cosmic-microwave-background-radiation', 'Arno Penzias and Robert Wilson discovered the cosmic microwave background in 1965 while investigating unexplained radio noise, a find that won them the 1978 Nobel Prize in Physics.', false),
  ('space-duration-jwst-earliest-galaxy', 'space', 'physics', 'duration', 'How many years after the Big Bang did the earliest galaxy ever confirmed emit its light?', 290000000, 50000000, 1000000000, 'log', 'duration-year', null, 'University of California, Santa Cruz - Earliest, Most Distant Galaxy Discovered With James Webb Space Telescope', 'https://news.ucsc.edu/2024/05/galaxy-jades-gs-z14-0/', 'The galaxy JADES-GS-z14-0 is seen as it existed just 290 million years after the Big Bang, when the universe was about 2% of its current age.', false),
  ('space-event-sagittarius-a-star-first-image', 'space', 'history', 'event', 'In what year was the first image of our own galaxy''s black hole released?', 2022, 1990, 2025, 'linear', 'year', null, 'Event Horizon Telescope - Astronomers Reveal First Image of the Black Hole at the Heart of Our Galaxy', 'https://eventhorizontelescope.org/blog/astronomers-reveal-first-image-black-hole-heart-our-galaxy', 'In May 2022, the Event Horizon Telescope collaboration released the first image of Sagittarius A*, the supermassive black hole at the centre of the Milky Way, three years after imaging M87''s black hole.', false),
  ('space-count-messier-catalog-objects', 'space', 'quantity', 'count', 'Charles Messier catalogued fuzzy objects so he''d stop mistaking them for comets. How many are on the final list?', 110, 20, 300, 'linear', 'count', null, 'NASA HEASARC - Messier Catalog', 'https://heasarc.gsfc.nasa.gov/w3browse/all/messier.html', 'Messier''s original list of 103 objects was later expanded to 110, including famous targets like the Andromeda Galaxy, the Crab Nebula and the Orion Nebula.', false),
  ('space-mass-hubble-space-telescope', 'space', 'size', 'mass', 'What did the Hubble Space Telescope weigh at launch, in kilograms?', 11110, 2000, 50000, 'log', 'kilogram', null, 'ESA/Hubble - Fact Sheet', 'https://esahubble.org/about/general/fact_sheet/', 'Hubble had a launch mass of about 11,110 kilograms, roughly the weight of two loaded school buses, and was carried into orbit inside the Space Shuttle''s cargo bay.', false),
  ('space-speed-stardust-capsule-reentry', 'space', 'physics', 'speed', 'The Stardust capsule holds the record for fastest reentry by anything human-made. How fast, in kilometres per hour?', 46440, 10000, 100000, 'log', 'kph', null, 'NASA Jet Propulsion Laboratory - NASA''s Stardust Sample Return Was 10 Years Ago Today', 'https://www.jpl.nasa.gov/news/nasas-stardust-sample-return-was-10-years-ago-today/', 'The Stardust mission''s sample-return capsule re-entered Earth''s atmosphere at about 46,440 km/h in January 2006, the fastest reentry of any human-made object on record.', false),
  ('space-count-gemini-crewed-missions', 'space', 'quantity', 'count', 'How many crewed Gemini missions did NASA fly between Mercury and Apollo?', 10, 1, 30, 'linear', 'count', null, 'NASA - Project Gemini', 'https://www.nasa.gov/gemini/', 'NASA''s Gemini program flew ten crewed missions in 1965 and 1966, testing the rendezvous, docking and spacewalk skills that Apollo would need to reach the Moon.', false),
  ('space-speed-new-horizons-launch', 'space', 'physics', 'speed', 'New Horizons left Earth faster than any spacecraft before or since. How fast, in kilometres per hour?', 58338, 10000, 200000, 'log', 'kph', null, 'Guinness World Records - Fastest Earth Departure Speed', 'https://www.guinnessworldrecords.com/world-records/fastest-earth-departure-speed', 'New Horizons left Earth at about 58,338 km/h, the fastest launch speed of any spacecraft in history, and passed the Moon''s orbit in just nine hours.', false),
  ('space-event-chandrayaan-3-moon-landing', 'space', 'history', 'event', 'In what year did India''s Chandrayaan-3 become the first mission to land near the Moon''s south pole?', 2023, 1990, 2025, 'linear', 'year', null, 'NASA Science - Chandrayaan-3', 'https://science.nasa.gov/mission/chandrayaan-3/', 'ISRO''s Chandrayaan-3 mission landed near the Moon''s south pole on 23 August 2023, making India the fourth country to land on the Moon and the first to reach this far-south region.', false),
  ('space-mass-hayabusa2-ryugu-sample', 'space', 'size', 'mass', 'How much asteroid material did Japan''s Hayabusa2 bring back from Ryugu, in kilograms?', 0.0054, 0.0001, 1, 'log', 'kilogram', null, 'JAXA/ISAS - Hayabusa2 Ryugu Sample Curatorial Dataset', 'https://darts.isas.jaxa.jp/doi/curation/hayabusa2/desc/cur-ryugu-description_landing.html', 'Hayabusa2 returned about 5.4 grams, or 0.0054 kilograms, of material from asteroid Ryugu in December 2020, humanity''s largest sample yet from beyond the Earth-Moon system at the time.', false),
  ('space-duration-rosetta-comet-chase', 'space', 'physics', 'duration', 'How many years did ESA''s Rosetta spend chasing comet 67P before catching it?', 10, 1, 30, 'linear', 'duration-year', null, 'European Space Agency - Rosetta Overview', 'https://www.esa.int/Science_Exploration/Space_Science/Rosetta', 'Rosetta launched in 2004 and spent about ten years travelling through the Solar System, using gravity assists from Earth and Mars, before arriving at comet 67P/Churyumov-Gerasimenko in 2014.', false),
  ('space-count-kepler-90-planets', 'space', 'quantity', 'count', 'Kepler-90 was the first system found to tie our own planet count. How many planets does it have?', 8, 1, 15, 'linear', 'count', null, 'NASA Science - Discovery of Eight Planets Makes Alien System the First to Tie With Our Solar System', 'https://science.nasa.gov/universe/exoplanets/discovery-of-eight-planets-makes-alien-system-the-first-to-tie-with-our-solar-system/', 'The discovery of Kepler-90i, found using a Google-developed machine learning method, brought the Kepler-90 system''s planet count to eight, matching our own Solar System.', false),
  ('space-duration-proxima-centauri-b-orbit', 'space', 'physics', 'duration', 'How many days does Proxima Centauri b, the closest known exoplanet, take to orbit its star?', 11.2, 1, 100, 'linear', 'day', null, 'NASA Science - Proxima Centauri b', 'https://science.nasa.gov/exoplanet-catalog/proxima-centauri-b/', 'Proxima Centauri b, the closest known exoplanet to our Solar System, completes one orbit of its star in about 11.2 days.', false),
  ('movies-money-apollo-13-worldwide-box-office', 'movies', 'quantity', 'money', 'How much did Apollo 13 (1995) gross worldwide at the box office, in US dollars?', 355237933, 50000000, 1000000000, 'log', 'usd', '1995', 'The Numbers - Apollo 13 (1995) Box Office and Financial Information', 'https://www.the-numbers.com/movie/Apollo-13', 'Apollo 13 (1995) grossed about $355,237,933 worldwide at the box office, dramatising the real 1970 mission that turned a moon landing into a survival story.', false),
  ('movies-money-the-martian-worldwide-box-office', 'movies', 'quantity', 'money', 'How much did The Martian (2015) gross worldwide at the box office, in US dollars?', 631058917, 50000000, 1500000000, 'log', 'usd', '2015', 'Box Office Mojo - The Martian', 'https://www.boxofficemojo.com/release/rl3496969729/', 'The Martian (2015) grossed about $631,058,917 worldwide, becoming one of the highest-grossing space survival films ever made.', false)
on conflict (id) do nothing;
