-- Imported by scripts/import-questions.ts from C:\Users\Cambo\Downloads\16dinoapproved-questions.json.

insert into public.questions (
  id, category, measure, subtype, prompt, answer, min, max, scale, unit,
  reference_year, source_title, source_url, explanation, is_daily
) values
  ('dinosaurs-cretaceous-period-duration', 'dinosaurs', 'physics', 'duration', 'How many million years did the Cretaceous Period last?', 79000000, 30000000, 130000000, 'linear', 'duration-year', null, 'National Park Service — Cretaceous Period—145.0 to 66.0 MYA', 'https://www.nps.gov/articles/000/cretaceous-period.htm', 'The Cretaceous lasted about 79 million years, ending 66 million years ago with the mass extinction that eliminated all non-bird dinosaurs.', false),
  ('dinosaurs-deccan-traps-eruption-duration', 'dinosaurs', 'physics', 'duration', 'For roughly how many million years did the major Deccan Traps volcanic activity continue around the end of the dinosaur era?', 2000000, 100000, 20000000, 'log', 'duration-year', null, 'Natural History Museum — How an asteroid ended the age of the dinosaurs', 'https://www.nhm.ac.uk/discover/how-an-asteroid-caused-extinction-of-dinosaurs.html', 'The major Deccan Traps volcanic activity continued for about 2 million years, adding long-term climate stress before and around the asteroid impact.', false),
  ('dinosaurs-dippy-london-display-duration', 'dinosaurs', 'physics', 'duration', 'For roughly how many years had Dippy the Diplodocus been displayed in London before leaving for a UK tour?', 110, 50, 200, 'linear', 'duration-year', null, 'Natural History Museum — Dippy: this is your life', 'https://www.nhm.ac.uk/discover/diplodocus-this-is-your-life.html', 'Dippy had been displayed in London for more than 110 years, having been unveiled in 1905 before leaving public display in 2017.', false),
  ('dinosaurs-sue-custody-battle-duration', 'dinosaurs', 'physics', 'duration', 'How many years did the legal custody battle over SUE the T. rex last?', 5, 1, 15, 'linear', 'duration-year', null, 'Field Museum — SUE the T. rex', 'https://www.fieldmuseum.org/blog/sue-t-rex', 'The custody battle lasted 5 years and ended with SUE being sold at public auction in 1997.', false),
  ('dinosaurs-quarry-wall-fossil-age', 'dinosaurs', 'physics', 'duration', 'Approximately how many million years old are the fossils still embedded in the Quarry Wall at Dinosaur National Monument?', 150000000, 80000000, 250000000, 'linear', 'duration-year', null, 'National Park Service — Quarry Exhibit Hall', 'https://www.nps.gov/dino/planyourvisit/quarry-exhibit-hall.htm', 'The Quarry Wall fossils are approximately 150 million years old and come from the Late Jurassic Morrison Formation.', false),
  ('dinosaurs-sue-recovered-bone-count', 'dinosaurs', 'quantity', 'count', 'How many bones from the roughly 380-bone T. rex skeleton were recovered for SUE?', 250, 100, 600, 'linear', 'count', null, 'Field Museum — SUE the T. rex', 'https://www.fieldmuseum.org/blog/sue-t-rex', 'SUE preserves 250 of the roughly 380 known bones in a T. rex skeleton, including the wishbone and belly ribs.', false),
  ('dinosaurs-dippy-skeleton-bone-count', 'dinosaurs', 'quantity', 'count', 'How many bones make up London''s Dippy Diplodocus cast?', 292, 50, 400, 'linear', 'count', null, 'Natural History Museum — Dippy: this is your life', 'https://www.nhm.ac.uk/discover/diplodocus-this-is-your-life.html', 'Dippy is a 292-bone cast that arrived in London packed into 36 cases before its 1905 unveiling.', false),
  ('dinosaurs-crystal-palace-dinosaur-statue-count', 'dinosaurs', 'quantity', 'count', 'Despite the name, how many of the prehistoric animal statues at Crystal Palace Park actually represent dinosaurs?', 4, 1, 12, 'linear', 'count', null, 'Natural History Museum — Missing Crystal Palace mammal recreated decades after disappearance', 'https://www.nhm.ac.uk/discover/news/2023/july/missing-crystal-palace-mammal-recreated-decades-after-disappearance.html', 'Only 4 of the more than 30 Crystal Palace prehistoric statues represent dinosaurs; the rest include mammals, marine reptiles and other extinct animals.', false),
  ('dinosaurs-amnh-dinosaur-wing-specimen-count', 'dinosaurs', 'quantity', 'count', 'About how many specimens are displayed across the American Museum of Natural History''s two dinosaur-wing halls?', 100, 20, 180, 'linear', 'count', null, 'American Museum of Natural History — Hall of Ornithischian Dinosaurs', 'https://www.amnh.org/exhibitions/permanent/ornithischian-dinosaurs', 'The two halls display about 100 specimens, drawn from one of the world''s largest dinosaur fossil collections.', false),
  ('dinosaurs-trix-skeleton-completeness', 'dinosaurs', 'quantity', 'percentage', 'Approximately what percentage complete is Naturalis museum''s T. rex Trix when measured by bone volume?', 80, 0, 100, 'linear', 'percent', null, 'Naturalis — Persdossier de T. rex van Naturalis', 'https://www.naturalis.nl/over-ons/media/persdossier-t-rex-van-naturalis', 'Trix is approximately 80% complete by bone volume, placing the specimen among the world''s most complete T. rex skeletons.', false),
  ('dinosaurs-scotty-bones-recovered-percentage', 'dinosaurs', 'quantity', 'percentage', 'About what percentage of Scotty the T. rex''s fossilised bones were found at the Saskatchewan dig site?', 65, 0, 100, 'linear', 'percent', null, 'Government of Saskatchewan — The Most Massive T.Rex Ever Discovered Calls Saskatchewan Home', 'https://www.saskatchewan.ca/government/news-and-media/2019/march/26/scotty', 'About 65% of Scotty''s fossilised bones were recovered, making it one of the most complete T. rex skeletons found.', false),
  ('dinosaurs-horridus-skeleton-completeness', 'dinosaurs', 'quantity', 'percentage', 'What percentage complete is Melbourne Museum''s Triceratops skeleton Horridus?', 85, 0, 100, 'linear', 'percent', null, 'Museums Victoria — Horridus is here!', 'https://museumsvictoria.com.au/media-releases/horridus-is-here/', 'Horridus is 85% complete and includes 266 fossil bones plus an entire vertebral column.', false),
  ('dinosaurs-carnegie-original-fossil-percentage', 'dinosaurs', 'quantity', 'percentage', 'Approximately what percentage of the objects in Carnegie Museum''s Kamin Hall of Dinosaurs are original fossils?', 75, 0, 100, 'linear', 'percent', null, 'Carnegie Museum of Natural History — Daniel G. And Carole L. Kamin Hall of Dinosaurs', 'https://carnegiemnh.org/explore/kamin-hall-of-dinosaurs/', 'About 75% of the hall''s more than 230 displayed objects are original fossils rather than replicas.', false),
  ('dinosaurs-baryonyx-discovery-year', 'dinosaurs', 'history', 'event', 'In what year was Baryonyx first discovered in a Surrey clay pit?', 1983, 1900, 2025, 'linear', 'year', null, 'Natural History Museum — How did Baryonyx change what we knew about spinosaurs?', 'https://www.nhm.ac.uk/discover/how-did-baryonyx-change-what-we-knew-about-spinosaurs.html', 'Baryonyx was discovered in 1983 after fossil hunter William Walker spotted a giant claw protruding from rock in Surrey.', false),
  ('dinosaurs-deinonychus-naming-year', 'dinosaurs', 'history', 'event', 'In what year did John Ostrom discover and name Deinonychus?', 1969, 1850, 2025, 'linear', 'year', null, 'Yale Peabody Museum — Deinonychus', 'https://peabody.yale.edu/article/deinonychus', 'John Ostrom discovered and named Deinonychus in 1969, helping trigger the dinosaur renaissance and renew the dinosaur-bird connection.', false)
on conflict (id) do nothing;
