-- Adds 30 sourced, non-Daily Geography questions to the shared question bank.
-- Percentage bounds use the project-wide 0-100 slider rule.

insert into public.questions (
  id, category, measure, subtype, prompt, answer, min, max, scale, unit,
  reference_year, source_title, source_url, explanation, is_daily
) values
  ('geography-length-badwater-basin-elevation', 'geography', 'size', 'length', 'What is Badwater Basin''s elevation relative to sea level?', -86, -150, 50, 'linear', 'metre', null, 'U.S. National Park Service - Badwater Basin', 'https://www.nps.gov/places/badwater-basin.htm', 'Badwater Basin lies 86 metres below sea level, making it the lowest point in North America; the negative answer marks that below-sea-level elevation.', false),
  ('geography-length-crater-lake-depth', 'geography', 'size', 'length', 'What is the maximum depth of Crater Lake in Oregon?', 592, 100, 2000, 'log', 'metre', null, 'U.S. National Park Service - The World''s Deepest Lakes', 'https://www.nps.gov/crla/planyourvisit/upload/World-s-Deepest-Lakes-2017-508.pdf', 'Crater Lake reaches 592 metres at its deepest point, making it the deepest lake in the United States and one of the deepest on Earth.', false),
  ('geography-length-mauna-kea-base-to-peak', 'geography', 'size', 'length', 'How tall is Mauna Kea from its underwater base to its summit?', 10210, 1000, 20000, 'log', 'metre', null, 'NOAA Ocean Service - Highest Point on Earth', 'https://oceanservice.noaa.gov/facts/highestpoint.html', 'Measured from its base on the Pacific seafloor, Mauna Kea rises about 10,210 metres, taller base-to-peak than Mount Everest.', false),
  ('geography-length-uluru-rise', 'geography', 'size', 'length', 'How high does Uluru rise above the surrounding plain?', 340, 50, 1000, 'linear', 'metre', null, 'Parks Australia - Uluru-Kata Tjuta Media Handbook', 'https://parksaustralia.gov.au/uluru/pub/uluru-kata-tjuta-media-handbook.pdf', 'Uluru rises about 340 metres above the plain, while much of the same sandstone formation continues unseen beneath the ground.', false),
  ('geography-length-denali-elevation', 'geography', 'size', 'length', 'What is the elevation of Denali above sea level?', 6190, 1000, 10000, 'linear', 'metre', null, 'U.S. National Park Service - Measuring Earth Movements from the Denali Fault', 'https://home.nps.gov/articles/denali-fault-movement.htm', 'Denali reaches 6,190 metres above sea level, making it the highest mountain in North America.', false),
  ('geography-length-lake-tahoe-depth', 'geography', 'size', 'length', 'What is the maximum depth of Lake Tahoe?', 502, 50, 2000, 'log', 'metre', null, 'U.S. Geological Survey - Lake Tahoe Hydro Mapper', 'https://www.usgs.gov/media/images/lake-tahoe-hydro-mapper', 'Lake Tahoe descends to about 502 metres, or 1,645 feet, which makes it the second-deepest lake in the United States.', false),
  ('geography-length-australia-coastline', 'geography', 'size', 'length', 'Roughly how long is mainland Australia''s coastline, excluding small offshore islands?', 34000, 1000, 100000, 'log', 'kilometre', null, 'Geoscience Australia - Coasts and Estuaries', 'https://www.ga.gov.au/scientific-topics/marine/coasts-estuaries', 'Mainland Australia has roughly 34,000 kilometres of coastline when small offshore islands are excluded.', false),
  ('geography-length-great-salt-lake-depth', 'geography', 'size', 'length', 'Roughly how deep is the Great Salt Lake at its deepest?', 11, 1, 60, 'linear', 'metre', null, 'U.S. Geological Survey - Great Salt Lake Facts', 'https://www.usgs.gov/centers/utah-water-science-center/science/general-information-facts-news-publications-and-partners', 'The Great Salt Lake is surprisingly shallow: its maximum depth is about 35 feet, or roughly 11 metres.', false),
  ('geography-length-arctic-ocean-depth', 'geography', 'size', 'length', 'What is the maximum depth of the Arctic Ocean?', 5567, 500, 12000, 'log', 'metre', null, 'NOAA Ocean Service - The World''s Smallest Ocean', 'https://oceanservice.noaa.gov/facts/smallestocean.html', 'The Arctic Ocean reaches 5,567 metres at its deepest point, despite being the smallest and shallowest of the five ocean basins overall.', false),
  ('geography-length-andes', 'geography', 'size', 'length', 'Approximately how long is the Andes mountain range?', 7000, 1000, 20000, 'log', 'kilometre', null, 'NASA - Chilean Andes', 'https://www.nasa.gov/image-article/chilean-andes/', 'The Andes stretch about 7,000 kilometres along western South America, making them the longest continental mountain range.', false),
  ('geography-length-mid-ocean-ridge', 'geography', 'size', 'length', 'Approximately how long is Earth''s global mid-ocean ridge system?', 65000, 5000, 150000, 'log', 'kilometre', null, 'NOAA Ocean Exploration - Mid-Ocean Ridge', 'https://oceanexplorer.noaa.gov/ocean-fact/mid-ocean-ridge/', 'The connected mid-ocean ridge system runs for nearly 65,000 kilometres, with more than 90 percent of it hidden underwater.', false),
  ('geography-length-bering-strait-width', 'geography', 'size', 'length', 'About how wide is the Bering Strait between Alaska and Russia at its narrowest?', 85, 20, 200, 'linear', 'kilometre', null, 'NOAA Fisheries - The Strait Connecting the Pacific and Arctic Oceans', 'https://www.fisheries.noaa.gov/feature-story/strait-connecting-pacific-and-arctic-oceans-larger-previously-measured', 'Only about 85 kilometres separate mainland Alaska and Russia across the Bering Strait at their closest point.', false),
  ('geography-area-arctic-ocean', 'geography', 'size', 'area', 'Approximately what area does the Arctic Ocean cover?', 15600000, 1000000, 50000000, 'log', 'square-kilometre', null, 'NOAA Ocean Service - The World''s Smallest Ocean', 'https://oceanservice.noaa.gov/facts/smallestocean.html', 'The Arctic Ocean covers about 15.6 million square kilometres, an area roughly one and a half times the size of Europe.', false),
  ('geography-area-yosemite', 'geography', 'size', 'area', 'Approximately what area does Yosemite National Park cover?', 3074, 500, 20000, 'log', 'square-kilometre', null, 'U.S. National Park Service - Yosemite Park Statistics', 'https://www.nps.gov/yose/learn/management/statistics.htm', 'Yosemite covers about 3,074 square kilometres, converted from the National Park Service figure of 1,187 square miles.', false),
  ('geography-area-everglades', 'geography', 'size', 'area', 'Approximately what area does Everglades National Park cover?', 6242, 500, 30000, 'log', 'square-kilometre', null, 'U.S. National Park Service - Everglades Park Statistics', 'https://home.nps.gov/ever/learn/news/parkstatistics.htm', 'Everglades National Park spans about 6,242 square kilometres, converted from its official area of 2,410 square miles.', false),
  ('geography-area-australia', 'geography', 'size', 'area', 'What is the total area of Australia?', 7688287, 500000, 30000000, 'log', 'square-kilometre', null, 'Geoscience Australia - Australia''s Size Compared', 'https://www.ga.gov.au/scientific-topics/national-location-information/dimensions/australias-size-compared', 'Australia covers 7,688,287 square kilometres, accounting for about 5 percent of the world''s land area.', false),
  ('geography-area-great-lakes', 'geography', 'size', 'area', 'What is the combined water surface area of the five Great Lakes?', 244160, 10000, 2000000, 'log', 'square-kilometre', null, 'U.S. Environmental Protection Agency - Physical Features of the Great Lakes', 'https://www.epa.gov/greatlakes/physical-features-great-lakes', 'Together, Lakes Superior, Michigan, Huron, Erie and Ontario cover 244,160 square kilometres of water.', false),
  ('geography-area-surtsey', 'geography', 'size', 'area', 'Approximately what area does Iceland''s volcanic island of Surtsey cover?', 1.41, 0.1, 20, 'log', 'square-kilometre', null, 'UNESCO World Heritage Centre - Surtsey', 'https://whc.unesco.org/en/list/1267/', 'Surtsey covers about 1.41 square kilometres, or 141 hectares, after emerging from the sea during volcanic eruptions.', false),
  ('geography-count-japan-islands', 'geography', 'quantity', 'count', 'According to Japan''s 2022 digital-map survey, how many islands does Japan have?', 14125, 500, 50000, 'log', 'count', '2022', 'Geospatial Information Authority of Japan - Number of Islands in Japan', 'https://web1.gsi.go.jp/kihonjohochousa/islands_index.html', 'The 2022 survey counted 14,125 islands using digital mapping, more than double the total from the earlier paper-map count.', false),
  ('geography-count-philippines-islands', 'geography', 'quantity', 'count', 'According to the Philippine Department of Tourism''s 2026 listing, how many islands make up the Philippines?', 7641, 500, 30000, 'log', 'count', '2026', 'Philippine Department of Tourism - Island Hopping', 'https://www.tourism.gov.ph/article/island-hopping-0-21/', 'The Philippines consists of 7,641 islands, grouped into the three broad regions of Luzon, Visayas and Mindanao.', false),
  ('geography-count-danube-countries', 'geography', 'quantity', 'count', 'Through how many countries does the main Danube River flow?', 10, 1, 30, 'linear', 'count', null, 'International Commission for the Protection of the Danube River - Basin Overview', 'https://www.icpdr.org/danube-basin/danube-river-basin/danube-river-basin-overview-map', 'The main Danube flows through 10 countries; its wider drainage basin reaches nine more, making it the world''s most international river basin.', false),
  ('geography-count-nile-countries', 'geography', 'quantity', 'count', 'Through how many countries does the Nile River flow?', 11, 1, 30, 'linear', 'count', null, 'Nile Basin Initiative - Major Subbasins', 'https://nilebasin.org/en/media-center/maps/major-subbasins', 'The Nile flows through 11 countries across eastern and north-eastern Africa before reaching the Mediterranean Sea.', false),
  ('geography-count-african-un-members', 'geography', 'quantity', 'count', 'According to the UN''s 2025 count, how many African countries are United Nations members?', 54, 10, 100, 'linear', 'count', '2025', 'United Nations Dag Hammarskjold Library - African Countries', 'https://ask.un.org/faq/22882', 'The United Nations has 54 African member states, all of which belong to its African Group.', false),
  ('geography-count-eight-thousanders', 'geography', 'quantity', 'count', 'How many mountain peaks on Earth rise above 8,000 metres?', 14, 1, 40, 'linear', 'count', null, 'NASA Earth Observatory - 8,000-meter Peaks of the Himalaya and Karakoram', 'https://science.nasa.gov/earth/earth-observatory/8000-meter-peaks-of-the-himalaya-and-karakoram-82581/', 'There are 14 peaks above 8,000 metres, and every one lies in the Himalayan or Karakoram mountain ranges of Asia.', false),
  ('geography-percentage-world-forest-cover-2025', 'geography', 'quantity', 'percentage', 'What percentage of the world''s land area was covered by forest in 2025?', 31.81, 0, 100, 'linear', 'percent', '2025', 'UN Food and Agriculture Organization - Forest Area Indicator', 'https://www.fao.org/sustainable-development-goals-data-portal/data/indicators/indicator-1511---forest-area-as-a-percentage-of-total-land-area/en', 'Forests covered 31.81 percent of global land area in 2025, according to the UN Food and Agriculture Organization.', false),
  ('geography-percentage-world-mountain-cover', 'geography', 'quantity', 'percentage', 'Approximately what percentage of Earth''s land surface is covered by mountains?', 27, 0, 100, 'linear', 'percent', null, 'UN Food and Agriculture Organization Mountain Partnership - Forests', 'https://www.fao.org/mountain-partnership/our-work/thematic-areas/forests/en', 'Mountains cover around 27 percent of Earth''s land surface and supply freshwater to more than half of humanity.', false),
  ('geography-percentage-great-lakes-surface-freshwater', 'geography', 'quantity', 'percentage', 'About what percentage of the world''s surface freshwater is held by the Great Lakes?', 21, 0, 100, 'linear', 'percent', null, 'U.S. Environmental Protection Agency - Great Lakes Facts and Figures', 'https://www.epa.gov/greatlakes/great-lakes-facts-and-figures', 'The five Great Lakes hold about 21 percent of the world''s supply of surface freshwater by volume.', false),
  ('geography-percentage-antarctica-freshwater', 'geography', 'quantity', 'percentage', 'Approximately what percentage of Earth''s freshwater is held in Antarctica?', 70, 0, 100, 'linear', 'percent', null, 'NASA Jet Propulsion Laboratory - RADARSAT Maps Antarctica', 'https://www.jpl.nasa.gov/news/radarsat-begins-first-complete-detailed-map-of-antarctica/', 'Antarctica contains nearly 70 percent of Earth''s freshwater, locked in an ice sheet that covers almost the entire continent.', false),
  ('geography-event-mount-st-helens-eruption', 'geography', 'history', 'event', 'In what year did Mount St. Helens have its catastrophic modern eruption?', 1980, 1900, 2025, 'linear', 'year', null, 'U.S. Geological Survey - 1980 Cataclysmic Eruption', 'https://www.usgs.gov/volcanoes/mount-st.-helens/science/1980-cataclysmic-eruption', 'Mount St. Helens erupted catastrophically on 18 May 1980, triggering the largest landslide in recorded history.', false),
  ('geography-event-surtsey-formation', 'geography', 'history', 'event', 'In what year did the volcanic island of Surtsey first emerge above the sea?', 1963, 1900, 2025, 'linear', 'year', null, 'UNESCO World Heritage Centre - Surtsey', 'https://whc.unesco.org/en/list/1267/', 'Surtsey first emerged off Iceland in 1963, and eruptions continued building the new island until 1967.', false);
